services:
  #  patients_db:
  #    image: mysql:8
  #    container_name: patients_db
  #    environment:
  #      MYSQL_ROOT_PASSWORD: choaib123
  #      MYSQL_DATABASE: patients_db
  #    ports:
  #      - "3307:3306"
  #    volumes:
  #      - patients_db_data:/var/lib/mysql
  #    networks:
  #      - db-network

  parametrage_db:
    image: mysql:8
    container_name: parametrage_db
    environment:
      MYSQL_ROOT_PASSWORD: choaib123
      MYSQL_DATABASE: parametrage_db
    ports:
      - "3304:3306"
    volumes:
      - parametrage_db_data:/var/lib/mysql
    networks:
      - db-network

networks:
  db-network:
    driver: bridge

volumes:
  #  patients_db_data:
  parametrage_db_data:
